instances:
  tf-controller01:
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      kubemanager:
      k8s_master:
  tf-compute01:
    roles:
      vrouter:
      k8s_node:
  tf-compute02:
    roles:
      vrouter:
      k8s_node:
contrail_configuration:
  CONTAINER_REGISTRY: opencontrailnightly
  CONTRAIL_VERSION: master-75
  UPGRADE_KERNEL: true